"""
   test filesystem
"""
print("newfs hello.dev 1024 100")
print("mount hello.dev")
print("ls")
print("mkdir fruits")
print("mkdir vegetables")
print("ls")
print("cd fruits")
print("cd .")
print("mkdir apples")
print("cd .")
print("ls")
print("unmount")
#
print("mount hello.dev")
print("ls")
print("cd vegetables")
print("mkdir broccoli")
print("mkdir carrot")
print("mkdir tomato")
print("ls")
print("unmount")
#
print("mount hello.dev")
print("ls")
print("cd fruits")
print("ls")
print("unmount")
#
print("mount hello.dev")
print("ls")
print("cd vegetables")
print("ls")
print("cd ..")
print("ls")
print("cd ..")
print("unmount")
print("quit")