"""
   test filesystem
"""
print("newfs hello.dev 1024 100")
print("mount hello.dev")
print("ls")
print("mkdir test1")
print("ls")
print("cd test1")
print("mkdir test3")
print("ls")
print("unmount")
print("mount hello.dev")
print("ls")
print("mkdir test2")
print("ls")
print("cd test1")
print("ls")
print("unmount")
print("quit")