print("help")

print("newfs hello.dev 512 512")
print("mount hello.dev")
print("iNodeMapFull")
print("setiNode 2")
print("allociNode")
print("allociNode")
print("freeiNode 0\nsetiNode 3\nfreeiNode 3\nfreeiNode 2")
print("iNodeMapFull")
print("unmount")
print("mount hello.dev")
print("iNodeMapFull")
print("unmount")

print("quit")